#                     _  _____ ______        _    _                   ______         _
#                    | ||  _  || ___ \      | |  | |                  | ___ \       | |
#   ___  ___    ___  | || | | || |_/ /_   _ | |_ | |__    ___   _ __  | |_/ /  ___  | |_
#  / __|/ _ \  / _ \ | || | | ||  __/| | | || __|| '_ \  / _ \ | '_ \ | ___ \ / _ \ | __|
# | (__| (_) || (_) || |\ \/' /| |   | |_| || |_ | | | || (_) || | | || |_/ /| (_) || |_
#  \___|\___/  \___/ |_| \_/\_\\_|    \__, | \__||_| |_| \___/ |_| |_|\____/  \___/  \__|
#                                      __/ |
#                                     |___/
#
# 机器人主配置文件，主要用于nonebot基础配置

#Debug相关设置
debug: true #开启logging中的debug级日志显示，会降低性能

#API相关设置
access_token: "" #访问授权，具体请查看CQHTTP文档
secret: "" #同上
host: 127.0.0.1 #反向ws监听地址，建议127.0.0.1
port: 8080 #反向ws端口
thread_pool_num: 64

#apscheduler相关设置，具体请查阅文档
apscheduler_config:
    apscheduler.timezone: Asia/Shanghai #设置时区，建议别动

#机器人逻辑回复相关设置
command_sep: [".", "/"] #命令分隔符，不知道有什么用
command_start: ["／", "!", "/", "！", "*", "-"] #标记一个命令开始
default_validation_failure_expression: 您的输入不符合要求，请重新输入 #输入验证失败时的回复，填空为不回复
max_validation_failures: 3 #最大验证失败次数
too_many_validation_failures_expression: 您输入错误太多次啦，如需重试，请重新触发本功能 #达到最大失败次数时的回复
nickname: [""] #机器人昵称，建议设置为空
session_cancel_expression: 好的 #用户控制会话提前结束回复，填空为不回复
session_expire_timeout: 300 #用户会话超时设置，单位为秒
session_run_timeout: null #会话运行超时设置，单位为秒，设空为不计超时
session_running_expression: 您有命令正在执行，请稍后再试 #当用户发出下一指令时上一会话仍在运行时提示
short_message_max_length: 50 #“短消息”的最大长度
superusers: [] #超级用户，即机器人管理员，具有最高权限
