apis:
    addresses: 
        - 'https://yande.re/post.json'
        - 'https://konachan.com/post.json'
        - 'https://danbooru.donmai.us/posts.json'
    retries: 5

send:
    range: 1000
    default: q
    size: 3

