apis:
    ascii2d: 'https://ascii2d.net/search/url/'
    retries: 5

customize:
    size: 3
    prefix: ''
    repeat: |
        ----------
        {preview}
        标题:{title}
        来自:{source} {id}
        {link}
    suffix: |
        ==========
        返回结果{size}个
        数据来自:ascii2d.net