# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Check

on:
  schedule:
    - cron: 0 0 * * 1
  push:
    branches:
      - master
      - bot-v2
      - bot-v3
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2
      
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Linters
      uses: samuelmeuli/lint-action@v1
      with:
        black: true
        flake8: true

    - name: Test with running file
      continue-on-error: true    
      run: |
        echo "Not implemented"
